url: "https://thetippingscales.github.io"

title: "The Tipping Scales"

plugins:
  - jekyll-paginate

paginate: 5

paginate_path: "/articles/page:num"

collections:
  tags:
    output: true
    permalink: /tags/:path/
  people:
    output: true
    permalink: /people/:path/

defaults:
  - scope:
      path: ''
      type: tags
    values:
      layout: tag
  - scope:
      path: ''
      type: people
    values:
      layout: person

page_excerpts: true

exclude:
  - README.md
  - LICENSE.md
  - /assets/icon/bootstrap-icons/LICENSE.md
  - /assets/icon/bootstrap-icons/README.md
